spring.application.name=notification-service


server.port=8082

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest


spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.otp_system.notification_service.kafka.event.OtpEvent



spring.kafka.consumer.properties.spring.json.trusted.packages=com.otp_system.notification_service.kafka.event


# Circuit Breaker
resilience4j.circuitbreaker.instances.smsService.sliding-window-size=10
resilience4j.circuitbreaker.instances.smsService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.smsService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.smsService.permitted-number-of-calls-in-half-open-state=3

# Retry
resilience4j.retry.instances.smsRetry.max-attempts=3
resilience4j.retry.instances.smsRetry.wait-duration=2s



# =========================
# Gmail SMTP Configuration
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abkashgangwar@gmail.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# =========================
# Kafka Dead Letter Topic
# =========================
spring.kafka.listener.ack-mode=record
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.concurrency=12
spring.kafka.consumer.max-poll-records=10




# Enable manual error handling (DLQ ready)
spring.kafka.consumer.enable-auto-commit=false

# Email Circuit Breaker
resilience4j.circuitbreaker.instances.emailService.sliding-window-size=10
resilience4j.circuitbreaker.instances.emailService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.emailService.wait-duration-in-open-state=10s

# Email Retry
resilience4j.retry.instances.emailRetry.max-attempts=3
resilience4j.retry.instances.emailRetry.wait-duration=2s
