services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: otpdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: zi6HvjXyQVma_ZxwARChpw
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # =========================
  # AUTH SERVICE (Scaled)
  # =========================
  auth:
    build: ./auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_PASSWORD: Root@1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
    # Scaling will be handled via --scale flag (docker compose does not support deploy.replicas)
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    expose:
      - "8081"

  # =========================
  # NOTIFICATION SERVICES (3 instances)
  # =========================
  notification:
    build: ./notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SMTP_PASSWORD: mbacmywdtwtqqreq
    # Scaling will be handled via --scale flag (docker compose does not support deploy.replicas)
    depends_on:
      kafka:
        condition: service_started
    expose:
      - "8082"

  # =========================
  # GATEWAY SERVICE
  # =========================
  gateway:
    build: ./gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    container_name: gateway
    depends_on:
      - auth
    ports:
      - "8080:8080"