spring.application.name=gateway
server.port=8080

# Global CORS Configuration
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedHeaders=*

spring.http.codecs.max-in-memory-size=1MB

# Gateway connection pool for high concurrency
spring.cloud.gateway.server.webflux.httpclient.pool.maxConnections=500

 # Route 1 - OTP SEND (moderate limit)
spring.cloud.gateway.server.webflux.routes[0].id=auth-service-send
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/otp/send
spring.cloud.gateway.server.webflux.routes[0].filters[0]=Retry=2,INTERNAL_SERVER_ERROR
spring.cloud.gateway.server.webflux.routes[0].filters[1]=CircuitBreaker=name=authCircuit,fallbackUri=forward:/fallback
spring.cloud.gateway.server.webflux.routes[0].filters[2].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.key-resolver=#{@phoneEmailKeyResolver}
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.redis-rate-limiter.burstCapacity=5

# Route 2 - OTP VERIFY (stricter limit)
spring.cloud.gateway.server.webflux.routes[1].id=auth-service-verify
spring.cloud.gateway.server.webflux.routes[1].uri=http://auth:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/otp/verify
spring.cloud.gateway.server.webflux.routes[1].filters[0]=Retry=2,INTERNAL_SERVER_ERROR
spring.cloud.gateway.server.webflux.routes[1].filters[1]=CircuitBreaker=name=authCircuit,fallbackUri=forward:/fallback
spring.cloud.gateway.server.webflux.routes[1].filters[2].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.key-resolver=#{@phoneEmailKeyResolver}
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.redis-rate-limiter.replenishRate=3
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.redis-rate-limiter.burstCapacity=3

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=2000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=3s


spring.main.web-application-type=reactive
#  Redis Connection
spring.data.redis.host=redis
spring.data.redis.port=6379


# Security Response Headers
spring.cloud.gateway.server.webflux.default-filters[0]=AddResponseHeader=X-Content-Type-Options,nosniff
spring.cloud.gateway.server.webflux.default-filters[1]=AddResponseHeader=X-Frame-Options,DENY
spring.cloud.gateway.server.webflux.default-filters[2]=AddResponseHeader=Strict-Transport-Security,max-age=63072000

logging.pattern.level=%5p [${spring.application.name:},%X{X-Correlation-Id}]